//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatAIFluentWpf.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://uchi-chataiwpf-kv.vault.azure.net/")]
        public string AzureKeyVaultUri {
            get {
                return ((string)(this["AzureKeyVaultUri"]));
            }
            set {
                this["AzureKeyVaultUri"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5deaea0f-acc6-4c71-aa8b-ccf5f1f3a343")]
        public string AzureClientID {
            get {
                return ((string)(this["AzureClientID"]));
            }
            set {
                this["AzureClientID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("39ff9aae-e121-4388-83f4-b66586365fdd")]
        public string AzureTenantID {
            get {
                return ((string)(this["AzureTenantID"]));
            }
            set {
                this["AzureTenantID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("IoU8Q~P-KiAcFvaEY~08BI~rgyhg_mmyywp~rbIB")]
        public string AzureClientSecret {
            get {
                return ((string)(this["AzureClientSecret"]));
            }
            set {
                this["AzureClientSecret"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int VoiceVoxSpeakerId {
            get {
                return ((int)(this["VoiceVoxSpeakerId"]));
            }
            set {
                this["VoiceVoxSpeakerId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5000")]
        public int SpeechServiceConnection_InitialSilenceTimeoutMs {
            get {
                return ((int)(this["SpeechServiceConnection_InitialSilenceTimeoutMs"]));
            }
            set {
                this["SpeechServiceConnection_InitialSilenceTimeoutMs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public int Speech_SegmentationSilenceTimeoutMs {
            get {
                return ((int)(this["Speech_SegmentationSilenceTimeoutMs"]));
            }
            set {
                this["Speech_SegmentationSilenceTimeoutMs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("あなたは日本語で会話ができるチャットボットです。")]
        public string InitialSystemPrompt {
            get {
                return ((string)(this["InitialSystemPrompt"]));
            }
            set {
                this["InitialSystemPrompt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AudioDeviceId {
            get {
                return ((string)(this["AudioDeviceId"]));
            }
            set {
                this["AudioDeviceId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150")]
        public int MaxTokens {
            get {
                return ((int)(this["MaxTokens"]));
            }
            set {
                this["MaxTokens"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.5")]
        public double Temperature {
            get {
                return ((double)(this["Temperature"]));
            }
            set {
                this["Temperature"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string WssProxy {
            get {
                return ((string)(this["WssProxy"]));
            }
            set {
                this["WssProxy"] = value;
            }
        }
    }
}
